name: Publish to CDN

on:
  push:
    tags: ['v*']
  workflow_dispatch: {}

concurrency:
  group: cdn-deploy
  cancel-in-progress: true

jobs:
  publish_to_cdn:
    name: Publish to CDN
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Publish to CDN
        uses: ./.github/workflows/publish-cdn.yml
        secrets: inherit