name: Run Semgrep
on:
  pull_request:
    branches:
      - "**"
concurrency:
  group: run-semgrep-${{ github.head_ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    if: (github.actor != 'dependabot[bot]')
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Run semgrep
        run: semgrep ci
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
          SEMGREP_BASELINE_REF: "master"

