name: Run Diffend
on:
  pull_request:
    branches:
      - "**"
concurrency:
  group: run-diffend-${{ github.head_ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["18.13.0"]
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Install Diffend (Mend)
        run: npm install -g https://my.diffend.io/releases/npm/stable.tgz
      - name: Install dependencies with Diffend
        run: diffend npm install

