name: Run tests
on:
  pull_request:
    branches:
      - "**"
concurrency:
  group: run-tests-${{ github.head_ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["16.17.0"]
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run test:all:parallel
        env:
          TEST_API_KEY: ${{ secrets.TEST_API_KEY }}
          RUN_NETWORK_TIMEOUT_TESTS: false
