name: Spell check

on:
  pull_request:
    branches:
      - "**"

concurrency:
  group: spell-check-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  check:
    name: Run spell check
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: ["18.13.0"]

    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Spell check
        run: npx cspell@v8.19.4 "**/*.js"
